// Generated by https://quicktype.io
import { JwtPayload } from "jsonwebtoken";
import { Request } from "express";
import { UserRegister } from "../interfaces/userRegister";

export interface id {
  id: string;
}

// export interface RequestNvo extends Request {
//   user?: JwtPayload & UserRegister;

// }
export interface ReqPorject extends RequestNvo {
  _id: id;
}
export interface _id {
  _id?: string | object | undefined;
}

export interface RequestNvo extends Request {
  user?: string | JwtPayload | null | id | object | undefined |any;
}

export interface RequestAuth extends Request {
  user?: string | null | UserRegister;
}

